title: Linda Carter Ranch Broker
author:
  name: Chris Loewer
  email: 'chris.loewer@gmail.com'
metadata:
    description: 'This is a website intended to serve as a landing page for the business of Linda Carter.  Linda is a ranch broker selling land throughout Texas.  This website is meant to showcase her company and the properties she has for sale.'

